{
 "title": "dashboards",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Потребление RAM",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_virtual_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Среднее предсказанное значение ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "main_app_predictions_sum / main_app_predictions_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество запросов в 5 минут",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "increase(main_app_predictions_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Общее количество запросов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "http_request_duration_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}